name: CD

on:
  push:
    branches: [ main ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm ci
    - run: npm run build

    - name: deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        exclude_assets: ''
